"""Canonical market/outcome taxonomy.

Both xGScore (probabilities) and Betclic (odds) use their own internal
naming for markets and outcomes. Rather than hardcoding site-specific
strings deep in the scraping code, every scraper normalizes whatever it
extracts into this canonical vocabulary using an *alias map* defined in
``config.yaml`` (see ``xgscore.market_aliases`` / ``betclic.market_aliases``).

That keeps calibration (matching real site output to canonical markets)
entirely in configuration -- no code changes needed when you inspect the
real pages and fill in the raw key names.

A canonical key is ``"<market>.<outcome>"``, e.g. ``"1x2.home"``,
``"btts.yes"``, ``"over_under_2.5.over"``, ``"correct_score.2-1"``.
"""

from __future__ import annotations

import re

# Human readable (PT-PT) labels for known markets/outcomes. Anything not
# listed here still works -- it just falls back to a title-cased version of
# the raw key so new/unknown markets degrade gracefully instead of breaking.
MARKET_LABELS: dict[str, str] = {
    "1x2": "Resultado Final",
    "double_chance": "Dupla Hipótese",
    "btts": "Ambas Marcam",
    "over_under_0.5": "Mais/Menos de 0.5 Golos",
    "over_under_1.5": "Mais/Menos de 1.5 Golos",
    "over_under_2.5": "Mais/Menos de 2.5 Golos",
    "over_under_3.5": "Mais/Menos de 3.5 Golos",
    "over_under_4.5": "Mais/Menos de 4.5 Golos",
    "half_time_result": "Resultado ao Intervalo",
    "correct_score": "Resultado Exato",
    "team_to_score_first": "Primeiro a Marcar",
    "goals_odd_even": "Total de Golos Par/Ímpar",
    "clean_sheet_home": "Casa Não Sofre Golo",
    "clean_sheet_away": "Fora Não Sofre Golo",
    "total_goals_exact": "Número Exato de Golos",
    "asian_handicap": "Handicap Asiático",
}

OUTCOME_LABELS: dict[str, str] = {
    "home": "Casa",
    "draw": "Empate",
    "away": "Fora",
    "yes": "Sim",
    "no": "Não",
    "over": "Mais",
    "under": "Menos",
    "1x": "Casa ou Empate",
    "12": "Casa ou Fora",
    "x2": "Empate ou Fora",
    "odd": "Ímpar",
    "even": "Par",
    "none": "Nenhuma",
}


#: (regex, PT label template) pairs for market *families* generated by
#: expand_array_market() below -- e.g. "over_under_3.5", "home_total_1.5"
#: -- where a fixed table can't list every possible line. Checked in
#: order, after an exact MARKET_LABELS hit and before the generic
#: title-cased fallback.
_MARKET_LABEL_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"^over_under_(?P<line>\d+(?:\.\d+)?)$"), "Mais/Menos de {line} Golos"),
    (re.compile(r"^home_total_(?P<line>\d+(?:\.\d+)?)$"), "Total Casa Mais/Menos de {line}"),
    (re.compile(r"^away_total_(?P<line>\d+(?:\.\d+)?)$"), "Total Fora Mais/Menos de {line}"),
    (re.compile(r"^handicap_home$"), "Handicap Casa"),
    (re.compile(r"^handicap_away$"), "Handicap Fora"),
]


def market_label(market: str) -> str:
    if market in MARKET_LABELS:
        return MARKET_LABELS[market]
    for pattern, template in _MARKET_LABEL_PATTERNS:
        m = pattern.match(market)
        if m:
            return template.format(**m.groupdict())
    return market.replace("_", " ").title()


def outcome_label(market: str, outcome: str) -> str:
    return OUTCOME_LABELS.get(outcome, outcome.replace("_", " ").title())


def full_label(market: str, outcome: str) -> str:
    return f"{market_label(market)} - {outcome_label(market, outcome)}"


def normalize_markets(
    raw: dict[str, float], alias_map: dict[str, str]
) -> dict[str, dict[str, float]]:
    """Turn ``{raw_key: value}`` into ``{market: {outcome: value}}``.

    ``alias_map`` maps a raw key exactly as scraped (a CSS-extracted field
    name, or a dotted JSON path resolved by the extractor) to a canonical
    ``"market.outcome"`` string, e.g.::

        {"prob_home_win": "1x2.home", "btts_yes_pct": "btts.yes"}

    Raw keys with no alias are dropped silently (they're usually page
    chrome / unrelated numbers) -- run ``scripts/inspect_site.py`` and
    extend the alias map in ``config.yaml`` if a market you care about is
    missing from the output.
    """
    out: dict[str, dict[str, float]] = {}
    for raw_key, value in raw.items():
        canonical = alias_map.get(raw_key)
        if not canonical or "." not in canonical:
            continue
        # rsplit, not split: the *market* half can itself contain a dot
        # (e.g. "over_under_2.5.over" -> market "over_under_2.5", outcome
        # "over") -- only the outcome (the last segment) never does.
        market, outcome = canonical.rsplit(".", 1)
        out.setdefault(market, {})[outcome] = value
    return out


def expand_array_market(
    rows: list, market_template: str, outcome_template: str
) -> dict[str, dict[str, float]]:
    """Expand one whole market array into several canonical entries at once.

    Some markets ship as a *list* of ``[label, value, ...]`` rows sharing
    one shape -- every over/under line, every handicap line, etc. --
    which would be tedious (and, for a line-per-market/config-field
    scheme, unbounded) to enumerate one at a time. Instead, one config.yaml
    rule names the whole array's json_path plus two Python ``.format()``
    templates that turn each row's own ``label`` into a canonical
    ``market``/``outcome`` pair, e.g.::

        rows = [["0.5", 94.8, ...], ["2.5", 63.9, ...]]
        expand_array_market(rows, "over_under_{label}", "over")
        # -> {"over_under_0.5": {"over": 0.948}, "over_under_2.5": {"over": 0.639}}

        rows = [["-2.5", 15.8, ...], ["0", 71.5, ...]]
        expand_array_market(rows, "handicap_home", "{label}")
        # -> {"handicap_home": {"-2.5": 0.158, "0": 0.715}}

    Values are *always* 0..100 percentages here (confirmed: xGScore's own
    arrays report tail probabilities like 0.8 meaning 0.8%, not a
    fraction) and are unconditionally divided by 100 -- deliberately
    *not* the ``value / 100.0 if value > 1.0 else value`` heuristic
    ``normalize_probabilities()`` uses elsewhere, which would silently
    misread a legitimate small percentage like that 0.8 as an
    already-a-fraction 80%. That heuristic exists there only because it
    has to guess at a flat, mixed-purpose ``{key: value}`` dict with no
    other context; here every row comes from the same one convention, so
    there's nothing to guess.

    A malformed row (not a ``[label, value, ...]`` list, or a non-numeric
    value) is skipped rather than raising -- one bad row in an otherwise
    good array shouldn't drop the whole thing.
    """
    out: dict[str, dict[str, float]] = {}
    for row in rows:
        if not isinstance(row, (list, tuple)) or len(row) < 2:
            continue
        label, value = row[0], row[1]
        if not isinstance(value, (int, float)):
            continue
        market = market_template.format(label=label)
        outcome = outcome_template.format(label=label)
        out.setdefault(market, {})[outcome] = value / 100.0
    return out


def merge_markets(*market_maps: dict[str, dict[str, float]]) -> dict[str, dict[str, float]]:
    merged: dict[str, dict[str, float]] = {}
    for mm in market_maps:
        for market, outcomes in mm.items():
            merged.setdefault(market, {}).update(outcomes)
    return merged
